/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    ADrawer: typeof import('ant-design-vue/es')['Drawer']
    AEmpty: typeof import('ant-design-vue/es')['Empty']
    APagination: typeof import('ant-design-vue/es')['Pagination']
    ASpin: typeof import('ant-design-vue/es')['Spin']
    ATabPane: typeof import('ant-design-vue/es')['TabPane']
    ATabs: typeof import('ant-design-vue/es')['Tabs']
    Button: typeof import('./src/components/button/index.vue')['default']
    Carousel: typeof import('./src/components/carousel/index.vue')['default']
    Drawer: typeof import('./src/components/header/components/drawer/index.vue')['default']
    Float: typeof import('./src/components/structure/left-rigth/float/index.vue')['default']
    Footer: typeof import('./src/components/footer/index.vue')['default']
    Half: typeof import('./src/components/structure/left-rigth/half/index.vue')['default']
    Header: typeof import('./src/components/header/index.vue')['default']
    LeftRigth: typeof import('./src/components/structure/left-rigth/index.vue')['default']
    Menu: typeof import('./src/components/header/components/menu/index.vue')['default']
    Paragraph: typeof import('./src/components/structure/left-rigth/half/paragraph/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Step: typeof import('./src/components/step/index.vue')['default']
    Title: typeof import('./src/components/header/title/index.vue')['default']
  }
}
